# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build, lint and run

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Run linter
        uses: cpp-linter/cpp-linter-action@v2.11.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 18
          database: build # The directory containing the compile_commands.json file.
          style: "" # disable clang-format checks.
          tidy-checks: "" # Use .clang-tidy config file
          file-annotations: true
          thread-comments: true
          ignore: .github|build
          files-changed-only: true

      - name: Build
        run: cmake --build build

      - name: Run
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ./test_main
